# Generated by Django 3.1.1 on 2020-09-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=200)),
                ('time', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to=None)),
            ],
        ),
    ]
