# Generated by Django 3.1.1 on 2020-09-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='zip_code',
        ),
    ]
