# Generated by Django 3.1.1 on 2020-09-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_contact_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=250)),
                ('post_content', models.TextField()),
                ('post_desc', models.CharField(default='', max_length=500)),
                ('post_author', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(max_length=200)),
                ('post_time', models.DateField(auto_now_add=True)),
                ('post_thumbnail', models.ImageField(upload_to='blog/img')),
            ],
        ),
    ]
