# Generated by Django 3.1.1 on 2020-09-22 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200921_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id_post',
            new_name='slug',
        ),
    ]
