# Generated by Django 3.1.1 on 2020-09-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200922_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
