# Generated by Django 3.1.1 on 2020-09-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200924_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
